# Site
title: 晴晴晴-Nicole Wu
description: This is Nicole's blog.
logo: favicon.ico
url: ''
rss_url: /feed.xml

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Social Links
email:              super571@sina.com
#google.plus:       username
twitter:            du571
#facebook:          username
github:             niki571
stackoverflow:      6528774/nicole-wu   #from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          nicolewu571
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
youtube:            miao571
#soundcloud:        username
weibo:              goodgirlsgotoheaven
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile,.sass-cache,.DS_Store,.idea]
